import { Prisma, ChallengeTaskPattern } from '@prisma/client';

import { season } from '../season';
import { theWinningCrewChallenge } from '../challenges';
import { challenge1Task6 } from './challenge1Tasks';
import { V } from './constants';

type Configuration = Record<string, any> & {
  anyGamesAmount?: number;
  setupGamesAmount?: number;
  oneVsOneGamesAmount?: {
    likeOppenent: boolean;
    likeOwner: boolean;
    amount: number;
  };
  upDownGamesAmount?: number;
  x1000GamesAmount?: number;
  bullsEyeGamesAmount?: number;
}

export const challenge4Task1: Prisma.ChallengeTaskCreateInput = {
  id: 'challenge4Task1',
  name: 'Trooper',
  description: `Win any 3 games on Xyro.`,
  number: 1,
  reward: V * 1,
  configuration: {
    anyGamesAmount: 3,
  } as Configuration,
  pattern: ChallengeTaskPattern.WON_GAMES,
  challenge: {
    connect: {
      id: theWinningCrewChallenge.id,
    },
  },
  season: {
    connect: {
      id: season.id,
    }
  },
  blockedByTask: {
    connect: {
      id: challenge1Task6.id,
    }
  }
};

export const challenge4Task2: Prisma.ChallengeTaskCreateInput = {
  id: 'challenge4Task2',
  name: 'Slayer',
  description: `a. Win 3 Up/Down games;\nb. Win 2 Setup games;\nc. Win 1 1vs1 game.`,
  number: 2,
  reward: V * 5,
  configuration: {
    upDownGamesAmount: 3,
    setupGamesAmount: 2,
    oneVsOneGamesAmount: {
      amount: 1,
      likeOppenent: true,
      likeOwner: true,
    },
  } as Configuration,
  pattern: ChallengeTaskPattern.WON_GAMES,
  challenge: {
    connect: {
      id: theWinningCrewChallenge.id,
    },
  },
  season: {
    connect: {
      id: season.id,
    }
  },
  blockedByTask: {
    connect: {
      id: challenge4Task1.id,
    }
  }
};

export const challenge4Task3: Prisma.ChallengeTaskCreateInput = {
  id: 'challenge4Task3',
  name: 'Assassin',
  description: `a. Win 10 Up/Down games;\nb. Win 5 Setup games;\nc. Close 1 1000x position in profit.`,
  number: 3,
  reward: V * 10,
  configuration: {
    upDownGamesAmount: 10,
    setupGamesAmount: 5,
    x1000GamesAmount: 1,
  } as Configuration,
  pattern: ChallengeTaskPattern.WON_GAMES,
  challenge: {
    connect: {
      id: theWinningCrewChallenge.id,
    },
  },
  season: {
    connect: {
      id: season.id,
    }
  },
  blockedByTask: {
    connect: {
      id: challenge4Task2.id,
    }
  }
};

export const challenge4Task4: Prisma.ChallengeTaskCreateInput = {
  id: 'challenge4Task4',
  name: 'Destroyer',
  description: `a. Win any 20 games on Xyro;\nb. Win 1 Bull's Eye game;\nc. Close 3 1000x positions in profit.`,
  number: 4,
  reward: V * 15,
  configuration: {
    anyGamesAmount: 20,
    bullsEyeGamesAmount: 1,
    x1000GamesAmount: 3,
  } as Configuration,
  pattern: ChallengeTaskPattern.WON_GAMES,
  challenge: {
    connect: {
      id: theWinningCrewChallenge.id,
    },
  },
  season: {
    connect: {
      id: season.id,
    }
  },
  blockedByTask: {
    connect: {
      id: challenge4Task3.id,
    }
  }
};

export const challenge4Task5: Prisma.ChallengeTaskCreateInput = {
  id: 'challenge4Task5',
  name: 'Terminator',
  description: `a. Win any 50 games on Xyro;\nb. Win 5 1vs1 games generated by you;\nc. Win 3 Bull's Eye games.`,
  number: 5,
  reward: V * 25,
  configuration: {
    anyGamesAmount: 50,
    oneVsOneGamesAmount: {
      amount: 5,
      likeOppenent: false,
      likeOwner: true,
    },
    bullsEyeGamesAmount: 3,
  } as Configuration,
  pattern: ChallengeTaskPattern.WON_GAMES,
  challenge: {
    connect: {
      id: theWinningCrewChallenge.id,
    },
  },
  season: {
    connect: {
      id: season.id,
    }
  },
  blockedByTask: {
    connect: {
      id: challenge4Task4.id,
    }
  }
};
