export const GRPC_USERS_SERVICE_TOKEN = 'GRPC_USERS_SERVICE_TOKEN';
export const GRPC_LEDGER_SERVICE_TOKEN = 'GRPC_LEDGER_SERVICE_TOKEN';
export const GRPC_BULLS_EYE_SERVICE_TOKEN = 'GRPC_BULLS_EYE_SERVICE_TOKEN';
export const GRPC_ANALYTICS_SERVICE_TOKEN = 'GRPC_ANALYTICS_SERVICE_TOKEN';
export const GRPC_MODULE_OPTIONS_TOKEN = 'GRPC_MODULE_OPTIONS_TOKEN';
