export const GRPC_ANALYTICS_SERVICE_URL = 'GRPC_ANALYTICS_SERVICE_URL';
export const GRPC_USERS_SERVICE_TOKEN = 'GRPC_USERS_SERVICE_TOKEN';
export const GRPC_MODULE_OPTIONS_TOKEN = 'GRPC_MODULE_OPTIONS_TOKEN';
