syntax = "proto3";

package ledger;

service LedgerService {
  rpc GetUserBalance(GetUserBalancePayload) returns (Balance) {}
  rpc GetLedgerAccountById(GetLedgerAccountByIdPayload) returns (LedgerAccount) {}
  rpc GetUserLedgerAccount(GetUserLedgerAccountPayload) returns (LedgerAccount) {}
}

message GetUserBalancePayload {
  string userId = 1;
}

message Balance {
  string id = 1;
  string accountId = 2;
  double amount = 3;
}

message GetLedgerAccountByIdPayload {
  string accountId = 1;
}

message GetUserLedgerAccountPayload {
  string userId = 1;
}

message LedgerAccount {
  string id = 1;
  optional string parentId = 2;
  string name = 4;
  string fullName = 5;
}
