export const GRPC_USERS_SERVICE_TOKEN = 'GRPC_USERS_SERVICE_TOKEN';
export const GRPC_MESSENGER_SERVICE_TOKEN = 'GRPC_MESSENGER_SERVICE_TOKEN';
export const GRPC_LEDGER_SERVICE_TOKEN = 'GRPC_LEDGER_SERVICE_TOKEN';
export const GRPC_TWITTER_SERVICE_TOKEN = 'GRPC_TWITTER_SERVICE_TOKEN';
export const GRPC_MODULE_OPTIONS_TOKEN = 'GRPC_MODULE_OPTIONS_TOKEN';
