-- CreateEnum
CREATE TYPE "ChallengeTaskPattern" AS ENUM ('ENRICH_PROFILE', 'CONNECT_WITH_X', 'SHARE_CHALLENGE', 'DISCORD_CHALLENGE', 'COMMUNITY_CHALLENGE', 'INVITE_USERS', 'PLAY_ANY_GAME', 'PLAY_SETUP_GAMES', 'CREATE_CHAT_MESSAGES', 'WON_GAMES', 'WHALE_SQUAD', 'SOCIAL_TRIBE_CHALLENGE', 'SHAROOOORS_INVITE_SHARE', 'SHAROOOORS_PLAY_SHARE', 'SHAROOOORS_CREATE_SHARE', 'SHAROOOORS_WIN_SHARE');

-- AlterTable
ALTER TABLE "ChallengeTask" ADD COLUMN     "reward" DECIMAL(65,30) NOT NULL,
DROP COLUMN "pattern",
ADD COLUMN     "pattern" "ChallengeTaskPattern" NOT NULL,
ALTER COLUMN "configuration" DROP NOT NULL;
