export enum GraphQLEntitiesNames {
  Asset = 'Asset',
  AssetPrice = 'AssetPrice',
  Candle = 'Candle',
  Referral = 'Referral',
  Balance = 'Balance',
  BalanceOperation = 'BalanceOperation',
  User = 'User',
  TwitterAccount = 'TwitterAccount',
  PaymentOrder = 'PaymentOrder',
  PaymentTransaction = 'PaymentTransaction',
  Game = 'Game',
  Bet = 'Bet',
  Message = 'Message',
  Room = 'Room',
  UpDownGame = 'UpDownGame',
  UpDownBet = 'UpDownBet',
  UpDownGamePoolInfo = 'UpDownGamePoolInfo',
  SetupBet = 'SetupBet',
  SetupGame = 'SetupGame',
  SetupGamePoolInfo = 'SetupGamePoolInfo',
  BullsEyeGame = 'BullsEyeGame',
  BullsEyeBet = 'BullsEyeBet',
  BullsEyeGamePoolInfo = 'BullsEyeGamePoolInfo',
  OneVsOneGame = 'OneVsOneGame',
  OneVsOneBet = 'OneVsOneBet',
  X1000Game = 'X1000Game',
  X1000Bet = 'X1000Bet',
  Reward = 'Reward',
  SeasonChallenge = 'SeasonChallenge',
  Season = 'Season',
  ChallengeTask = 'ChallengeTask',
  UserChallengeTask = 'UserChallengeTask',
  ChallengeTaskConfiguration = 'ChallengeTaskConfiguration',
  WonGamesChallengeTaskConfiguration = 'WonGamesChallengeTaskConfiguration',


  Notification = 'Notification',
  GameResultNotificationPayload = 'GameResultNotificationPayload',
  MentionNotification = 'MentionNotification',
  HotNotification = 'HotNotification',
  GameResultNotification = 'GameResultNotification',
}

export enum GraphQLSubscriptionsEntitiesNames {
  X1000GameState = 'X1000GameState',
  AssetPriceState = 'AssetPriceState',
  NotificationState = 'NotificationState',
  MessageState = 'MessageState',
  BalanceState = 'BalanceState',
  UpDownGameState = 'UpDownGameState',
  PaymentOrderState = 'PaymentOrderState',
  PaymentTransactionState = 'PaymentTransactionState',
  OneVsOneGameState = 'OneVsOneGameState',
  BullsEyeGameState = 'BullsEyeGameState',
  BullsEyeStatePoolInfo = 'BullsEyeStatePoolInfo',
  BullsEyeGameStateMyBet = 'BullsEyeGameStateMyBet',
  BullsEyeGamesState = 'BullsEyeGamesState',
  BullsEyeGameStateMeta = 'BullsEyeGameStateMeta',
}
